// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef comp_ui_h
#define comp_ui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *main_window;
#include <FL/Fl_Button.H>
extern Fl_Button *btnRefFile;
#include <FL/Fl_File_Input.H>
extern Fl_File_Input *reference_file;
extern Fl_Button *btnCompFile;
extern Fl_File_Input *compare_file;
extern Fl_Button *btnCompare;
#include <FL/Fl_Output.H>
extern Fl_Output *txtREPORT;
extern Fl_Button *btnExit;
Fl_Double_Window* make_comptty_win();
#endif
